### ISSUE TITLE
Mapa

### ISSUE THREAD

**Issue by pierzchala** [thymikee/kp-website#2]
![screenshot-thymikee github io 2016-08-08 22-52-43](https://cloud.githubusercontent.com/assets/20886447/17495842/f12c11c6-5dba-11e6-93c6-224b5d959c17.png)

nie działa ani na desktopie ani na telefonie.

**Comment by thymikee** [comment]
Problem z defer, poprawione tutaj d461592b0e204777554288af873c89b38e912695
