### ISSUE TITLE
Linkowanie menu

### ISSUE THREAD

**Issue by pierzchala** [thymikee/kp-website#3]
![screenshot-thymikee github io 2016-08-08 22-55-09](https://cloud.githubusercontent.com/assets/20886447/17495914/3f91ca7c-5dbb-11e6-89b1-d1d92fceafa4.png)

Niech te linki przewijają stronę do odpowiednich modułów. Na przykład po kliknięciu na "Placówki" strona powinna się przewinąć do modułu "Placówek".

**Comment by thymikee** [comment]
Done 44231b2eed6eb87c855678dec239f2221b3462cd
